Item.create(name: "Vitamin Water", price: 10, quantity: 20, user_id: 27)
Item.create(name: "Soda", price: 20, quantity: 20, user_id: 27)
Item.create(name: "Iced Tea", price: 10, quantity: 20, user_id: 27)
Item.create(name: "Cold Coffee", price: 10, quantity: 20, user_id: 28)
Item.create(name: "Diet Soda", price: 20, quantity: 20, user_id: 27)
Item.create(name: "Gatorade", price: 30, quantity: 20, user_id: 27)
Item.create(name: "Noodles", price: 10, quantity: 20, user_id: 27)
Item.create(name: "Ice cream", price: 25, quantity: 20, user_id: 28)
Item.create(name: "Pizza", price: 5, quantity: 20, user_id: 28)
Item.create(name: "Raw Milk", price: 30, quantity: 20, user_id: 28)
Item.create(name: "Coke", price: 20, quantity: 20, user_id: 28)
Item.create(name: "Dairy milk", price: 10, quantity: 20, user_id: 28)
